### PR TITLE
🐎 Optimise iterators.

### LINKED ISSUE #11: Potential NullPointerException not caught in TrailDBIterator.next()
At line 47 of TrailDBIterator, in method next(), the call to `TrailDBNative.INSTANCE.cursorNext(TrailDBIterator.this.cursor);` may return null. The value is then used at line 50.
Check nullity and throw a NoSuchElementException as defined in Java's Iterator interface
https://docs.oracle.com/javase/7/docs/api/java/util/Iterator.html#next()

### PR DESCRIPTION
**Pull request by Nennya**
Instead of creating the events on the JNI side, do it on Java side and fill them from JNI. This speeds up the simple count iteration over the database by a factor of  ~1/3 on my machine.

Make the Iterator methods next and hasNext a bit cleaner. Closes #11 .

### CODE REVIEW

File: src/main/java/io/sqooba/traildb/TrailDB.java [hunk 1]
```diff
@@ -93,11 +93,11 @@ public long getMinTimestamp() {
...
      * Get the newest timestamp.
-     * 
+     *
      * @return The newest timestmap.
      */
     public long getMaxTimestamp() {
-        long max = this.trailDBj.maxTimestamp(this.db);
+        final long max = this.trailDBj.maxTimestamp(this.db);
         if (max < 0) {
             LOGGER.warn("long overflow, received a negtive value for max timestamp.");
```
Comment (ChrisJamesC) [inline src/main/java/io/sqooba/traildb/TrailDB.java]: negative

File: src/main/native/io_sqooba_traildb_TrailDBNative.cpp [hunk 2]
```diff
@@ -481,27 +486,30 @@ JNIEXPORT jobject JNICALL Java_io_sqooba_traildb_TrailDBNative_tdbCursorNext
...
+    }
+
+	env->SetLongField(jevent, JFID_traildbEvent_timestamp, timestamp);
+	env->SetLongField(jevent, JFID_traildbEvent_numItems, num_items);
+	env->SetObjectField(jevent, JFID_traildbEvent_items, newArray);
 
-	jlongArray result;
- 	result = env->NewLongArray(num_items);
-	env->SetLongArrayRegion(result, 0, num_items, items);
+    env->ReleaseLongArrayElements(newArray, narr, 0);
```
Comment (ChrisJamesC) [inline src/main/native/io_sqooba_traildb_TrailDBNative.cpp]: indentation
